version: "3.8"

services:
  web:
    container_name: my-portfolio-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # 開発用なのでソースをボリュームマウント
    volumes:
      # ローカルのカレントディレクトリをコンテナの /app にマウント
      - .:/app
      # node_modules はコンテナ内だけで管理するため、ホストにはマウントしない（競合防止）
      - /app/node_modules
    # dev サーバー起動コマンド
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
