version: "3.8"
services:
  portfolio-web:
    build: .
    container_name: nextjs-portfolio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    # 作業ディレクトリは一旦 /app にしておく（後でコンテナ内に入って操作）
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
